### ISSUE TITLE
Still have nans then use non negative option, any suggestions?

### ISSUE THREAD

**Issue by hadaev8** [VainF/pytorch-msssim#16]

**Comment by ryanstout** [comment]
Seeing the same issue, no NaN's going in.  Float32 data if that matters.

**Comment by VainF** [comment]
Hi @hadaev8 @ryanstout  

Could you provide your code to reproduce this bug?

**Comment by VainF** [comment]
v0.2 has been uploaded to pypi now. Please contact me if the issue still exists.

**Comment by hadaev8** [comment]
(there is no symmetric padding in pytorch)
Shouldnt it be replicate padding?

**Comment by hadaev8** [comment]
This is traceback im getting, any suggestions?

File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pytorch_msssim/ssim.py", line 291, in forward
    K=self.K)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pytorch_msssim/ssim.py", line 212, in ms_ssim
    ms_ssim_val = torch.prod( mcs_and_ssim ** weights.view(-1, 1, 1), dim=0 )
 (print_stack at /pytorch/torch/csrc/autograd/python_anomaly_mode.cpp:60)
Traceback (most recent call last):
  File "train.py", line 469, in <module>
    args.n_gpus, args.local_rank, args.group_name, hparams)
  File "train.py", line 396, in train
    loss.backward()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Function 'PowBackward1' returned nan values in its 0th output.
