### ISSUE TITLE
bug fix in ms_ssim code

### ISSUE THREAD

**Issue by grupesh** [VainF/pytorch-msssim#34]
In the file https://github.com/VainF/pytorch-msssim/blob/master/pytorch_msssim/ssim.py

![image](https://user-images.githubusercontent.com/61022872/156804104-439fced0-735f-4baa-b7ac-dc96b2addb4d.png)
line 206 should say weights = torch.tensor(...)

**Comment by trougnouf** [comment]
I get an error there too but your fix doesn't seem to work?
```
>>> weights = [0.448, 0.26]
>>> weights = torch.tensor(...)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Could not infer dtype of ellipsis
```

This is the error I get:
```
>>> MS_SSIM()(gt_pt, n_pt)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/lib/python3.10/site-packages/pytorch_msssim/ssim.py", line 308, in forward
    return ms_ssim(
  File "/usr/lib/python3.10/site-packages/pytorch_msssim/ssim.py", line 191, in ms_ssim
    raise ValueError(f"Input images should be 4-d or 5-d tensors, but got {X.shape}")
ValueError: Input images should be 4-d or 5-d tensors, but got torch.Size([3, 3464, 5202])
>>> MS_SSIM()(gt_pt.unsqueeze(0), n_pt.unsqueeze(0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/lib/python3.10/site-packages/pytorch_msssim/ssim.py", line 308, in forward
    return ms_ssim(
  File "/usr/lib/python3.10/site-packages/pytorch_msssim/ssim.py", line 206, in ms_ssim
    weights = torch.FloatTensor(weights, device=X.device, dtype=X.dtype)
TypeError: new() received an invalid combination of arguments - got (list, dtype=torch.dtype, device=torch.device), but expected one of:
 * (*, torch.device device)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, *, torch.device device)
      didn't match because some of the keywords were incorrect: dtype
 * (object data, *, torch.device device)
      didn't match because some of the keywords were incorrect: dtype
```
